# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  broker:
    image: emqx:latest
    ports:
      - 18083:18083
      - 1883:1883

  datamanager:
    build:
      context: ./DataManager
      dockerfile: ./Dockerfile
    environment:
      PORT: ${MANAGER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    environment:
      PORT: ${GATEWAY_PORT}
      GRPC_SERVER: "http://datamanager:${MANAGER_PORT}"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  mqttclient:
    build:
      context: ./MQTTClient
      dockerfile: ./Dockerfile
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}

  eventmanager:
    build:
      context: ./EventManager
      dockerfile: ./Dockerfile
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
