# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  gateway:
    build:
      context: ./Gateway
      dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
