# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  manager:
    build:
      context: ./DataManager
      dockerfile: ./Dockerfile
    environment:
      PORT: ${MANAGER_PORT}
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    environment:
      PORT: ${GATEWAY_PORT}
      GRPC_SERVER: "http://manager:${MANAGER_PORT}"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
