// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "datamanager.proto" (syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { PowerConsumptionReport } from "./datamanager";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service DataManager
 */
export interface IDataManager extends grpc.UntypedServiceImplementation {
    /**
     * @generated from protobuf rpc: PostPowerConsumption
     */
    postPowerConsumption: grpc.handleUnaryCall<PowerConsumptionReport, Empty>;
}
/**
 * @grpc/grpc-js definition for the protobuf service DataManager.
 *
 * Usage: Implement the interface IDataManager and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IDataManager = ...
 * server.addService(dataManagerDefinition, service);
 * ```
 */
export const dataManagerDefinition: grpc.ServiceDefinition<IDataManager> = {
    postPowerConsumption: {
        path: "/DataManager/PostPowerConsumption",
        originalName: "PostPowerConsumption",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Empty.fromBinary(bytes),
        requestDeserialize: bytes => PowerConsumptionReport.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Empty.toBinary(value)),
        requestSerialize: value => Buffer.from(PowerConsumptionReport.toBinary(value))
    }
};
