[package]
name = "SensorGenerator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
csv = "1.3.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = "1.0.228"
serde_json = "1.0.145"
